import unittest
from contextlib import contextmanager

from tests.utils import TestExamplesMain
from advent_of_code.year_2022.day_12 import (part_1,
                                             part_2)


@contextmanager
def mocked_get_input(year, day):
    yield """abcccccccaaaaaccccaaaaaaaccccccccccccccccccccccccccccccccccccaaaaa\nabaacccaaaaaaccccccaaaaaaaaaaaaaccccccccccccccccccccccccccccaaaaaa\nabaacccaaaaaaaccccaaaaaaaaaaaaaacccccccccccccaacccccccccccccaaaaaa\nabaacccccaaaaaacaaaaaaaaaaaaaaaacccccccccccccaacccccccccccccacacaa\nabaccccccaaccaacaaaaaaaaaacccaacccccccccccccaaacccccccccccccccccaa\nabcccccccaaaacccaaaaaaaaacccccccccccccaaacccaaacccccccccccccccccaa\nabccccccccaaaccccccccaaaacccccccccccccaaaaacaaaccacacccccccccccccc\nabccccccccaaacaaacccccaaacccccccccccccaaaaaaajjjjjkkkcccccaacccccc\nabcccccaaaaaaaaaacccccaaccccccccccciiiiiijjjjjjjjjkkkcaaaaaacccccc\nabcccccaaaaaaaaacccccccccccccccccciiiiiiijjjjjjjrrkkkkaaaaaaaacccc\nabcccccccaaaaaccccccccccccccccccciiiiiiiijjjjrrrrrppkkkaaaaaaacccc\nabcccaaccaaaaaacccccccccccaacaaciiiiqqqqqrrrrrrrrpppkkkaaaaaaacccc\nabccaaaaaaaaaaaaccccacccccaaaaaciiiqqqqqqrrrrrruuppppkkaaaaacccccc\nabcccaaaaaaacaaaacaaacccccaaaaaahiiqqqqtttrrruuuuupppkkaaaaacccccc\nabcaaaaaaaccccaaaaaaacccccaaaaaahhqqqtttttuuuuuuuuuppkkkccaacccccc\nabcaaaaaaaaccccaaaaaacccccaaaaaahhqqqtttttuuuuxxuuuppkklcccccccccc\nabcaaaaaaaacaaaaaaaaaaacccccaaachhhqqtttxxxuuxxyyuuppllllccccccccc\nabcccaaacaccaaaaaaaaaaaccccccccchhhqqtttxxxxxxxyuupppplllccccccccc\nabaacaacccccaaaaaaaaaaaccccccccchhhqqtttxxxxxxyyvvvpppplllcccccccc\nabaacccccccccaaaaaaacccccccccccchhhpppttxxxxxyyyvvvvpqqqlllccccccc\nSbaaccccccaaaaaaaaaaccccccccccchhhppptttxxxEzzyyyyvvvqqqlllccccccc\nabaaaaccccaaaaaaaaacccccccccccchhhpppsssxxxyyyyyyyyvvvqqqlllcccccc\nabaaaacccccaaaaaaaacccccccccccgggpppsssxxyyyyyyyyyvvvvqqqlllcccccc\nabaaacccaaaacaaaaaaaccccccccccgggpppsswwwwwwyyyvvvvvvqqqllllcccccc\nabaaccccaaaacaaccaaaacccccccccgggppssswwwwwwyyywvvvvqqqqmmmccccccc\nabaaccccaaaacaaccaaaaccaaaccccggpppssssswwswwyywvqqqqqqmmmmccccccc\nabcccccccaaacccccaaacccaaacaccgggpppssssssswwwwwwrqqmmmmmccccccccc\nabcccccccccccccccccccaacaaaaacgggppooosssssrwwwwrrrmmmmmcccccccccc\nabcccccccccccccccccccaaaaaaaacggggoooooooorrrwwwrrnmmmdddccaaccccc\nabaccccccccccccaacccccaaaaaccccggggoooooooorrrrrrrnmmddddcaaaccccc\nabaccccccccaaaaaaccccccaaaaaccccggfffffooooorrrrrnnndddddaaaaccccc\nabaacccccccaaaaaacccccaaaaaacccccffffffffoonrrrrrnnndddaaaaaaacccc\nabaaccccccccaaaaaaaccacaaaacccccccccffffffonnnnnnnndddaaaaaaaacccc\nabccccccccccaaaaaaaaaaaaaaaccccccccccccfffennnnnnnddddccaaaccccccc\nabcccccccccaaaaaaacaaaaaaaaaacccccccccccffeennnnnedddccccaaccccccc\nabcccccccccaaaaaaccaaaaaaaaaaaccccccccccaeeeeeeeeeedcccccccccccccc\nabccccccccccccaaaccaaaaaaaaaaaccccccccccaaaeeeeeeeecccccccccccccaa\nabcccccccaaccccccccaaaaaaaacccccccccccccaaaceeeeecccccccccccccccaa\nabaaccaaaaaaccccccccaaaaaaaacccccccccccccaccccaaacccccccccccaaacaa\nabaaccaaaaacccccaaaaaaaaaaacccccccccccccccccccccacccccccccccaaaaaa\nabaccaaaaaaaaccaaaaaaaaaaaaaacccccccccccccccccccccccccccccccaaaaaa\n"""


class TestExamples(TestExamplesMain):

    @classmethod
    def setUpClass(cls):
        super().setUpClassAndPatch(2022, 12, mocked_get_input)

    def test_part1(self):
        """Test if example from part 1 problem statement works"""
        self.assertEqual(part_1.main(), 339)

    def test_part2(self):
        """Test if example from part 2 problem statement works"""
        self.assertEqual(part_2.main(), 332)

if __name__ == "__main__":
    unittest.main()